### ISSUE TITLE
Cannot load mitmproxy certificate

### ISSUE THREAD

**Issue by gavingrey** [Cryolite/mahjongsoul_sniffer#89]
This is the issue I am facing when trying to load `game-abstract-crawler`:

```
game-abstract-crawler-crawler-1   | + openssl x509 -in /home/ubuntu/.mitmproxy/mitmproxy-ca-cert.pem -inform PEM -out /home/ubuntu/mitmproxy-ca-cert.crt
game-abstract-crawler-crawler-1   | Could not open file or uri for loading certificate from /home/ubuntu/.mitmproxy/mitmproxy-ca-cert.pem
game-abstract-crawler-crawler-1   | 40A7E7F64F7F0000:error:16000069:STORE routines:ossl_store_get0_loader_int:unregistered scheme:../crypto/store/store_register.c:237:scheme=file
game-abstract-crawler-crawler-1   | 40A7E7F64F7F0000:error:80000002:system library:file_open:No such file or directory:../providers/implementations/storemgmt/file_store.c:267:calling stat(/home/ubuntu/.mitmproxy/mitmproxy-ca-cert.pem)
game-abstract-crawler-crawler-1   | Unable to load certificate
game-abstract-crawler-crawler-1   | + bin/run-chromedriver-once.py
game-abstract-crawler-crawler-1   | /opt/mahjongsoul-sniffer/bin/run-chromedriver-once.py:9: DeprecationWarning: headless property is deprecated, instead use add_argument('--headless') or add_argument('--headless=new')
game-abstract-crawler-crawler-1   |   options.headless = True
game-abstract-crawler-crawler-1   | + certutil -A -n mitmproxy -t TCu,Cu,Tu -i /home/ubuntu/mitmproxy-ca-cert.crt -d sql:/home/ubuntu/.pki/nssdb
game-abstract-crawler-crawler-1   | certutil:  unable to open "/home/ubuntu/mitmproxy-ca-cert.crt" for reading (-5950, 2).
game-abstract-crawler-crawler-1   | + game-abstract-crawler/crawler.py
game-abstract-crawler-crawler-1   | Traceback (most recent call last):
game-abstract-crawler-crawler-1   |   File "/opt/mahjongsoul-sniffer/game-abstract-crawler/crawler.py", line 23, in <module>
game-abstract-crawler-crawler-1   |     from mahjongsoul_sniffer.yostar_login import YostarLogin
game-abstract-crawler-crawler-1   |   File "/opt/mahjongsoul-sniffer/mahjongsoul_sniffer/yostar_login.py", line 9, in <module>
game-abstract-crawler-crawler-1   |     import mahjongsoul_sniffer.s3 as s3_
game-abstract-crawler-crawler-1   |   File "/opt/mahjongsoul-sniffer/mahjongsoul_sniffer/s3.py", line 15, in <module>
game-abstract-crawler-crawler-1   |     import mahjongsoul_sniffer.game_detail as game_detail_
game-abstract-crawler-crawler-1   |   File "/opt/mahjongsoul-sniffer/mahjongsoul_sniffer/game_detail.py", line 11, in <module>
game-abstract-crawler-crawler-1   |     from mahjongsoul_sniffer.mahjongsoul_pb2 \
game-abstract-crawler-crawler-1   |   File "/opt/mahjongsoul-sniffer/mahjongsoul_sniffer/mahjongsoul_pb2.py", line 33, in <module>
game-abstract-crawler-crawler-1   |     _descriptor.EnumValueDescriptor(
game-abstract-crawler-crawler-1   |   File "/usr/local/lib/python3.10/dist-packages/google/protobuf/descriptor.py", line 796, in __new__
game-abstract-crawler-crawler-1   |     _message.Message._CheckCalledFromGeneratedFile()
game-abstract-crawler-crawler-1   | TypeError: Descriptors cannot not be created directly.
game-abstract-crawler-crawler-1   | If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
game-abstract-crawler-crawler-1   | If you cannot immediately regenerate your protos, some other possible workarounds are:
game-abstract-crawler-crawler-1   |  1. Downgrade the protobuf package to 3.20.x or lower.
game-abstract-crawler-crawler-1   |  2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
game-abstract-crawler-crawler-1   | 
game-abstract-crawler-crawler-1   | More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
game-abstract-crawler-crawler-1 exited with code 1
```

Accessing the host on port 5000 shows no logs for crawler or sniffer.

**Comment by GrandDuke1106** [comment]
In the mahjongsoul_sniffer/bin/run-with-sniffer file, I changed the ```sleep 15```  to ```sleep 25``` to avoid this problem.

**Comment by gavingrey** [comment]
Thanks for following up. I looked but could not find mitmproxy version 7.3.0. Instead I modified `crawler.Dockerfile` to remove the previous mitmproxy installation and added the line `pip3 install mitmproxy==7.0.3`. However, I still get the same error.

**Comment by GrandDuke1106** [comment]
Yes, this is my fault.

In ```crawler.Dockerfile```. I changed ```mitmproxy``` to ```mitmproxy==7.0.3```, and changed ```sleep 15``` to ```sleep 25```, and I can find the certificate file in the running container. 

![image](https://github.com/Cryolite/mahjongsoul_sniffer/assets/98164810/d895a789-2475-4ac3-9f8e-0b07431c8598)

**Comment by gavingrey** [comment]
This solved my issue
